### ISSUE TITLE
Pls tweak xajax-project.org

### ISSUE THREAD

**Issue by CNSKnight** [Xajax/Xajax#31]
``` css
#content_right {
    float: left;
    margin-left: 10px;
    width: 65%;
}
```
